### PR TITLE
Take care of response type reading response text

### LINKED ISSUE #320: FileUpload problem with responseText and response type is arraybuffer
**Describe the bug**
An exception is happening when server is throwing an internal error (500) and the responseType is other than text

**To Reproduce**
1. Create FileUpload
2. Add
````
fileItem.addBeforeUploadHandler((request, form) -> {
                            request.responseType = "arraybuffer";
                        });
3. Upload file
````

**Expected behavior**
Launch errorHandlers from fileItem

**Screenshots**
imagen

imagen
FileItem

**Desktop (please complete the following information):**

### PR DESCRIPTION
**Pull request by RaulPampliegaMayoral**
Response text can be readed when response type is empty string or "text".
See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseText

Fix #320

### CODE REVIEW

**Comment by rjeeb** [comment]
@RaulPampliegaMayoral We need to give the ability to make this easier to extend, i.e. your case is valid and can be used by many developers, so it is obvious that we need to provide this as an API in a way that can be extendable and also easy to use.

I didn't work on that yet, but I'll try to work on that in these couple of days. Thanks

**Comment by rjeeb** [comment]
@RaulPampliegaMayoral We only read the response text when trying to get the error message, yet we provide an error handler for handling the error and we pass the request itself for that, so the developer has two options:

- Set an error handler and invalidate the field.
- Set a generic error message for invalidation for default behavior.

So i think we don't need the logic for reading the response text at all because we give the ability to read it from the developer side using the error handler and we also provide a default error message (same as success message).

Thank you for your effort in this and I'll be very happy if you change the fix to return the error message if it is not null and default error message if not set.

File: domino-ui/src/main/java/org/dominokit/domino/ui/upload/FileItem.java [hunk 1]
```diff
@@ -352,7 +352,9 @@ private void onError() {
     private String getErrorMessage() {
         if (errorMessage != null)
             return errorMessage;
-        return request.responseText.isEmpty() ? "Error while sending request" : request.responseText;
+        
+        final boolean hasErrorText = request.responseType != null && (request.responseType.isEmpty() || request.responseType.equals("text")) && !request.responseText.isEmpty();
+        return hasErrorText ? request.responseText : "Error while sending request";
```
Comment (rjeeb) [inline domino-ui/src/main/java/org/dominokit/domino/ui/upload/FileItem.java]: We only need to return the error message if it is not null and a default message if null.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral You have any more thoughts in this regard.
we are trying not to close the PR to keep the credit to you as the author of the commit, can you please elaborate more on this?

**Comment by RaulPampliegaMayoral** [comment]
Hi @vegegoku 
You can raise an exception without this PR if:
- You set the response type as any other than text or "".
- An error from server ocurred
- Default error message has not been set in FileItem component.

You cannot check for null the response text if the correct response type has not been set (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseText), so i think this PR resolve this case.

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku you can close the PR if you consider that is covered by the existing options. I can solve the issue #320 setting the default message error in every file item.
As i said this PR solves the case when the default message has not been set and the response type is other than text, but its true that setting the default message solves the problem
